
package com.supcon.orchid.WOM.wsSyncPutInMaterial;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.12
 * 2017-08-04T21:59:13.226+08:00
 * Generated source version: 3.1.12
 * 
 */
public final class ZMES008_ZMES008_Client {

    private static final QName SERVICE_NAME = new QName("urn:sap-com:document:sap:soap:functions:mc-style", "ZMES008");

    private ZMES008_ZMES008_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = ZMES008_Service.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        ZMES008_Service ss = new ZMES008_Service(wsdlURL, SERVICE_NAME);
        ZMES008 port = ss.getZMES008();  
        
        {
        System.out.println("Invoking zMesGetGi...");
        com.supcon.orchid.WOM.wsSyncPutInMaterial.Zmes008Stru2 _zMesGetGi_wInput = null;
        javax.xml.ws.Holder<java.lang.String> _zMesGetGi_message = new javax.xml.ws.Holder<java.lang.String>();
        javax.xml.ws.Holder<java.lang.String> _zMesGetGi_sflag = new javax.xml.ws.Holder<java.lang.String>();
        port.zMesGetGi(_zMesGetGi_wInput, _zMesGetGi_message, _zMesGetGi_sflag);

        System.out.println("zMesGetGi._zMesGetGi_message=" + _zMesGetGi_message.value);
        System.out.println("zMesGetGi._zMesGetGi_sflag=" + _zMesGetGi_sflag.value);

        }

        System.exit(0);
    }

}
