
package com.supcon.orchid.WOM.wsSyncPutInMaterial;

import javax.xml.ws.Endpoint;

/**
 * This class was generated by Apache CXF 3.1.12
 * 2017-08-04T21:59:13.258+08:00
 * Generated source version: 3.1.12
 * 
 */
 
public class ZMES008_ZMES008_Server{

    protected ZMES008_ZMES008_Server() throws java.lang.Exception {
        System.out.println("Starting Server");
        Object implementor = new ZMES008Impl();
        String address = "http://skssapdev.skshu.com.cn:8000/sap/bc/srt/rfc/sap/zmes008/800/zmes008/zmes008";
        Endpoint.publish(address, implementor);
    }
    
    public static void main(String args[]) throws java.lang.Exception { 
        new ZMES008_ZMES008_Server();
        System.out.println("Server ready..."); 
        
        Thread.sleep(5 * 60 * 1000); 
        System.out.println("Server exiting");
        System.exit(0);
    }
}
