
package com.supcon.orchid.WOM.sapWs;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import java.net.MalformedURLException;
import java.net.URL;

/**
 * This class was generated by Apache CXF 3.1.11
 * 2019-07-09T19:40:11.357+08:00
 * Generated source version: 3.1.11
 * 
 */
@WebServiceClient(name = "ZFG_MM_NSHMES", 
                  wsdlLocation = "file:/C:/nsh_sap.wsdl",
                  targetNamespace = "urn:sap-com:document:sap:rfc:functions") 
public class ZFGMMNSHMES_Service extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("urn:sap-com:document:sap:rfc:functions", "ZFG_MM_NSHMES");
    public final static QName ZFGMMNSHMESSoap12 = new QName("urn:sap-com:document:sap:rfc:functions", "ZFG_MM_NSHMES_soap12");
    public final static QName ZFGMMNSHMES = new QName("urn:sap-com:document:sap:rfc:functions", "ZFG_MM_NSHMES");
    static {
        URL url = null;
        try {
            url = new URL("file:/C:/nsh_sap.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(ZFGMMNSHMES_Service.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/C:/nsh_sap.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public ZFGMMNSHMES_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public ZFGMMNSHMES_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ZFGMMNSHMES_Service() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public ZFGMMNSHMES_Service(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public ZFGMMNSHMES_Service(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public ZFGMMNSHMES_Service(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns ZFGMMNSHMES
     */
    @WebEndpoint(name = "ZFG_MM_NSHMES_soap12")
    public ZFGMMNSHMES getZFGMMNSHMESSoap12() {
        return super.getPort(ZFGMMNSHMESSoap12, ZFGMMNSHMES.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ZFGMMNSHMES
     */
    @WebEndpoint(name = "ZFG_MM_NSHMES_soap12")
    public ZFGMMNSHMES getZFGMMNSHMESSoap12(WebServiceFeature... features) {
        return super.getPort(ZFGMMNSHMESSoap12, ZFGMMNSHMES.class, features);
    }


    /**
     *
     * @return
     *     returns ZFGMMNSHMES
     */
    @WebEndpoint(name = "ZFG_MM_NSHMES")
    public ZFGMMNSHMES getZFGMMNSHMES() {
        return super.getPort(ZFGMMNSHMES, ZFGMMNSHMES.class);
    }

    /**
     *
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ZFGMMNSHMES
     */
    @WebEndpoint(name = "ZFG_MM_NSHMES")
    public ZFGMMNSHMES getZFGMMNSHMES(WebServiceFeature... features) {
        return super.getPort(ZFGMMNSHMES, ZFGMMNSHMES.class, features);
    }

}
