
package com.supcon.orchid.WOM.sapWs;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.11
 * 2019-07-09T19:40:11.351+08:00
 * Generated source version: 3.1.11
 * 
 */
@WebService(targetNamespace = "urn:sap-com:document:sap:rfc:functions", name = "ZFG_MM_NSHMES")
@XmlSeeAlso({ObjectFactory.class})
public interface ZFGMMNSHMES {

    @WebMethod(operationName = "ZFM_MM_NSHMES_002", action = "urn:sap-com:document:sap:rfc:functions:ZFG_MM_NSHMES:ZFM_MM_NSHMES_002Request")
    @RequestWrapper(localName = "ZFM_MM_NSHMES_002", targetNamespace = "urn:sap-com:document:sap:rfc:functions", className = "com.ZFMMMNSHMES002")
    @ResponseWrapper(localName = "ZFM_MM_NSHMES_002Response", targetNamespace = "urn:sap-com:document:sap:rfc:functions", className = "com.ZFMMMNSHMES002Response")
    @WebResult(name = "OUTPUT", targetNamespace = "")
    public String zfmMMNSHMES002(
            @WebParam(name = "INPUT", targetNamespace = "")
                    String input
    );

    @WebMethod(operationName = "ZFM_MM_NSHMES_003", action = "urn:sap-com:document:sap:rfc:functions:ZFG_MM_NSHMES:ZFM_MM_NSHMES_003Request")
    @RequestWrapper(localName = "ZFM_MM_NSHMES_003", targetNamespace = "urn:sap-com:document:sap:rfc:functions", className = "com.ZFMMMNSHMES003")
    @ResponseWrapper(localName = "ZFM_MM_NSHMES_003Response", targetNamespace = "urn:sap-com:document:sap:rfc:functions", className = "com.ZFMMMNSHMES003Response")
    @WebResult(name = "OUTPUT", targetNamespace = "")
    public String zfmMMNSHMES003(
            @WebParam(name = "INPUT", targetNamespace = "")
                    String input
    );

    @WebMethod(operationName = "ZFM_MM_NSHMES_004", action = "urn:sap-com:document:sap:rfc:functions:ZFG_MM_NSHMES:ZFM_MM_NSHMES_004Request")
    @RequestWrapper(localName = "ZFM_MM_NSHMES_004", targetNamespace = "urn:sap-com:document:sap:rfc:functions", className = "com.ZFMMMNSHMES004")
    @ResponseWrapper(localName = "ZFM_MM_NSHMES_004Response", targetNamespace = "urn:sap-com:document:sap:rfc:functions", className = "com.ZFMMMNSHMES004Response")
    @WebResult(name = "OUTPUT", targetNamespace = "")
    public String zfmMMNSHMES004(
            @WebParam(name = "INPUT", targetNamespace = "")
                    String input
    );

    @WebMethod(operationName = "ZFM_MM_NSHMES_005", action = "urn:sap-com:document:sap:rfc:functions:ZFG_MM_NSHMES:ZFM_MM_NSHMES_005Request")
    @RequestWrapper(localName = "ZFM_MM_NSHMES_005", targetNamespace = "urn:sap-com:document:sap:rfc:functions", className = "com.ZFMMMNSHMES005")
    @ResponseWrapper(localName = "ZFM_MM_NSHMES_005Response", targetNamespace = "urn:sap-com:document:sap:rfc:functions", className = "com.ZFMMMNSHMES005Response")
    @WebResult(name = "OUTPUT", targetNamespace = "")
    public String zfmMMNSHMES005(
            @WebParam(name = "INPUT", targetNamespace = "")
                    String input
    );

    @WebMethod(operationName = "ZFM_MM_NSHMES_001", action = "urn:sap-com:document:sap:rfc:functions:ZFG_MM_NSHMES:ZFM_MM_NSHMES_001Request")
    @RequestWrapper(localName = "ZFM_MM_NSHMES_001", targetNamespace = "urn:sap-com:document:sap:rfc:functions", className = "com.ZFMMMNSHMES001")
    @ResponseWrapper(localName = "ZFM_MM_NSHMES_001Response", targetNamespace = "urn:sap-com:document:sap:rfc:functions", className = "com.ZFMMMNSHMES001Response")
    @WebResult(name = "OUTPUT", targetNamespace = "")
    public String zfmMMNSHMES001(
            @WebParam(name = "INPUT", targetNamespace = "")
                    String input
    );
}
