
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package com.supcon.orchid.WOM.webservise.wsSyncTaskPayRecouse;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.12
 * 2017-07-31T09:10:06.730+08:00
 * Generated source version: 3.1.12
 * 
 */

@javax.jws.WebService(
                      serviceName = "ZMES009",
                      portName = "ZMES009",
                      targetNamespace = "urn:sap-com:document:sap:soap:functions:mc-style",
                      wsdlLocation = "file:/D:/sksintetface/pags/doc99.wsdl",
                      endpointInterface = "com.supcon.orchid.WOM.wsSyncTaskReporting.ZMES009")
                      
public class ZMES009Impl implements ZMES009 {

    private static final Logger LOG = Logger.getLogger(ZMES009Impl.class.getName());

    /* (non-Javadoc)
     * @see com.supcon.orchid.WOM.wsSyncTaskReporting.ZMES009#zMesGetGr(com.supcon.orchid.WOM.wsSyncTaskReporting.Zmes009Stru wInput, java.lang.String message, java.lang.String sflag)*
     */
    public void zMesGetGr(com.supcon.orchid.WOM.webservise.wsSyncTaskPayRecouse.Zmes009Stru wInput, javax.xml.ws.Holder<java.lang.String> message, javax.xml.ws.Holder<java.lang.String> sflag) { 
        LOG.info("Executing operation zMesGetGr");
        System.out.println(wInput);
        try {
            java.lang.String messageValue = "";
            message.value = messageValue;
            java.lang.String sflagValue = "";
            sflag.value = sflagValue;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
