package com.supcon.orchid.WOM.webservise.wsSyncTaskPayRecouse;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.1.12
 * 2017-07-31T09:10:06.764+08:00
 * Generated source version: 3.1.12
 * 
 */
@WebServiceClient(name = "ZMES009", 
                  wsdlLocation = "file:/D:/sksintetface/pags/doc99.wsdl",
                  targetNamespace = "urn:sap-com:document:sap:soap:functions:mc-style") 
public class ZMES009_Service extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("urn:sap-com:document:sap:soap:functions:mc-style", "ZMES009");
    public final static QName ZMES009 = new QName("urn:sap-com:document:sap:soap:functions:mc-style", "ZMES009");
    static {
        URL url = null;
        try {
            url = new URL("file:/D:/sksintetface/pags/doc99.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(ZMES009_Service.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/D:/sksintetface/pags/doc99.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public ZMES009_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public ZMES009_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ZMES009_Service() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public ZMES009_Service(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public ZMES009_Service(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public ZMES009_Service(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns ZMES009
     */
    @WebEndpoint(name = "ZMES009")
    public ZMES009 getZMES009() {
        return super.getPort(ZMES009, ZMES009.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ZMES009
     */
    @WebEndpoint(name = "ZMES009")
    public ZMES009 getZMES009(WebServiceFeature... features) {
        return super.getPort(ZMES009, ZMES009.class, features);
    }

}
