
package com.supcon.orchid.WOM.wsSyncMaterAllot;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.12
 * 2017-07-29T17:19:38.476+08:00
 * Generated source version: 3.1.12
 * 
 */
public final class ZMES007_ZMES007_Client {

    private static final QName SERVICE_NAME = new QName("urn:sap-com:document:sap:soap:functions:mc-style", "ZMES007");

    private ZMES007_ZMES007_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = ZMES007_Service.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        ZMES007_Service ss = new ZMES007_Service(wsdlURL, SERVICE_NAME);
        ZMES007 port = ss.getZMES007();  
        
        {
        System.out.println("Invoking zMesGetStocktr...");
        com.supcon.orchid.WOM.wsSyncMaterAllot.Zmes007Stru _zMesGetStocktr_wInput = null;
        javax.xml.ws.Holder<java.lang.String> _zMesGetStocktr_message = new javax.xml.ws.Holder<java.lang.String>();
        javax.xml.ws.Holder<java.lang.String> _zMesGetStocktr_sflag = new javax.xml.ws.Holder<java.lang.String>();
        port.zMesGetStocktr(_zMesGetStocktr_wInput, _zMesGetStocktr_message, _zMesGetStocktr_sflag);

        System.out.println("zMesGetStocktr._zMesGetStocktr_message=" + _zMesGetStocktr_message.value);
        System.out.println("zMesGetStocktr._zMesGetStocktr_sflag=" + _zMesGetStocktr_sflag.value);

        }

        System.exit(0);
    }

}
