
package com.supcon.orchid.WOM.wsSyncMaterAllot;

import javax.xml.ws.Endpoint;

/**
 * This class was generated by Apache CXF 3.1.12
 * 2017-07-29T17:19:38.536+08:00
 * Generated source version: 3.1.12
 * 
 */
 
public class ZMES007_ZMES007_Server{

    protected ZMES007_ZMES007_Server() throws java.lang.Exception {
        System.out.println("Starting Server");
        Object implementor = new ZMES007Impl();
        String address = "http://skssapdev.skshu.com.cn:8000/sap/bc/srt/rfc/sap/zmes007/800/zmes007/zmes007";
        Endpoint.publish(address, implementor);
    }
    
    public static void main(String args[]) throws java.lang.Exception { 
        new ZMES007_ZMES007_Server();
        System.out.println("Server ready..."); 
        
        Thread.sleep(5 * 60 * 1000); 
        System.out.println("Server exiting");
        System.exit(0);
    }
}
