package com.supcon.orchid.WOM.wsSyncMaterAllot;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.1.12
 * 2017-07-29T17:19:38.549+08:00
 * Generated source version: 3.1.12
 * 
 */
@WebServiceClient(name = "ZMES007", 
                  wsdlLocation = "file:/D:/sksintetface/pags/doc77.wsdl",
                  targetNamespace = "urn:sap-com:document:sap:soap:functions:mc-style") 
public class ZMES007_Service extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("urn:sap-com:document:sap:soap:functions:mc-style", "ZMES007");
    public final static QName ZMES007 = new QName("urn:sap-com:document:sap:soap:functions:mc-style", "ZMES007");
    static {
        URL url = null;
        try {
            url = new URL("file:/D:/sksintetface/pags/doc77.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(ZMES007_Service.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/D:/sksintetface/pags/doc77.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public ZMES007_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public ZMES007_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ZMES007_Service() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public ZMES007_Service(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public ZMES007_Service(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public ZMES007_Service(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns ZMES007
     */
    @WebEndpoint(name = "ZMES007")
    public ZMES007 getZMES007() {
        return super.getPort(ZMES007, ZMES007.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ZMES007
     */
    @WebEndpoint(name = "ZMES007")
    public ZMES007 getZMES007(WebServiceFeature... features) {
        return super.getPort(ZMES007, ZMES007.class, features);
    }

}
