package com.supcon.orchid.WOM.wsSyncProduceInSingles;

import javax.xml.ws.Endpoint;

/**
 * This class was generated by Apache CXF 3.1.11
 * 2017-06-19T14:21:48.634+08:00
 * Generated source version: 3.1.11
 * 
 */
 
public class ZMES009_ZMES009_Server{

    protected ZMES009_ZMES009_Server() throws java.lang.Exception {
        System.out.println("Starting Server");
        Object implementor = new ZMES009Impl();
        String address = "http://skssapdev.skshu.com.cn:8000/sap/bc/srt/rfc/sap/zmes009/800/zmes009/zmes009";
        Endpoint.publish(address, implementor);
    }
    
    public static void main(String args[]) throws java.lang.Exception { 
        new ZMES009_ZMES009_Server();
        System.out.println("Server ready..."); 
        
        Thread.sleep(5 * 60 * 1000); 
        System.out.println("Server exiting");
        System.exit(0);
    }
}
