package com.supcon.orchid.WOM.webservise.wsSyncTaskFeedRecouse;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.1.12
 * 2017-07-29T17:37:14.783+08:00
 * Generated source version: 3.1.12
 * 
 */
@WebServiceClient(name = "ZMES008", 
                  wsdlLocation = "file:/D:/sksintetface/pags/doc88.wsdl",
                  targetNamespace = "urn:sap-com:document:sap:soap:functions:mc-style") 
public class ZMES008_Service extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("urn:sap-com:document:sap:soap:functions:mc-style", "ZMES008");
    public final static QName ZMES008 = new QName("urn:sap-com:document:sap:soap:functions:mc-style", "ZMES008");
    static {
        URL url = null;
        try {
            url = new URL("file:/D:/sksintetface/pags/doc88.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(ZMES008_Service.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/D:/sksintetface/pags/doc88.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public ZMES008_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public ZMES008_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ZMES008_Service() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public ZMES008_Service(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public ZMES008_Service(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public ZMES008_Service(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns ZMES008
     */
    @WebEndpoint(name = "ZMES008")
    public ZMES008 getZMES008() {
        return super.getPort(ZMES008, ZMES008.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ZMES008
     */
    @WebEndpoint(name = "ZMES008")
    public ZMES008 getZMES008(WebServiceFeature... features) {
        return super.getPort(ZMES008, ZMES008.class, features);
    }

}
