
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package com.supcon.orchid.WOM.webservise.wsSyncTaskFeedRecouse;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.12
 * 2017-07-29T17:37:14.739+08:00
 * Generated source version: 3.1.12
 * 
 */

@javax.jws.WebService(
                      serviceName = "ZMES008",
                      portName = "ZMES008",
                      targetNamespace = "urn:sap-com:document:sap:soap:functions:mc-style",
                      wsdlLocation = "file:/D:/sksintetface/pags/doc88.wsdl",
                      endpointInterface = "src.ZMES008")
                      
public class ZMES008Impl implements ZMES008 {

    private static final Logger LOG = Logger.getLogger(ZMES008Impl.class.getName());

    /* (non-Javadoc)
     * @see src.ZMES008#zMesGetGi(src.Zmes008Stru2 wInput, java.lang.String message, java.lang.String sflag)*
     */
    public void zMesGetGi(com.supcon.orchid.WOM.webservise.wsSyncTaskFeedRecouse.Zmes008Stru2 wInput, javax.xml.ws.Holder<java.lang.String> message, javax.xml.ws.Holder<java.lang.String> sflag) { 
        LOG.info("Executing operation zMesGetGi");
        System.out.println(wInput);
        try {
            java.lang.String messageValue = "";
            message.value = messageValue;
            java.lang.String sflagValue = "";
            sflag.value = sflagValue;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
